//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for address-category.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="address-category">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="atm"/>
 *     &lt;enumeration value="e-mail"/>
 *     &lt;enumeration value="lotus-notes"/>
 *     &lt;enumeration value="mac"/>
 *     &lt;enumeration value="sna"/>
 *     &lt;enumeration value="vm"/>
 *     &lt;enumeration value="ipv4-addr"/>
 *     &lt;enumeration value="ipv4-addr-hex"/>
 *     &lt;enumeration value="ipv4-net"/>
 *     &lt;enumeration value="ipv4-net-mask"/>
 *     &lt;enumeration value="ipv6-addr"/>
 *     &lt;enumeration value="ipv6-addr-hex"/>
 *     &lt;enumeration value="ipv6-net"/>
 *     &lt;enumeration value="ipv6-net-mask"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "address-category")
@XmlEnum
public enum AddressCategory {

    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("atm")
    ATM("atm"),
    @XmlEnumValue("e-mail")
    E_MAIL("e-mail"),
    @XmlEnumValue("lotus-notes")
    LOTUS_NOTES("lotus-notes"),
    @XmlEnumValue("mac")
    MAC("mac"),
    @XmlEnumValue("sna")
    SNA("sna"),
    @XmlEnumValue("vm")
    VM("vm"),
    @XmlEnumValue("ipv4-addr")
    IPV_4_ADDR("ipv4-addr"),
    @XmlEnumValue("ipv4-addr-hex")
    IPV_4_ADDR_HEX("ipv4-addr-hex"),
    @XmlEnumValue("ipv4-net")
    IPV_4_NET("ipv4-net"),
    @XmlEnumValue("ipv4-net-mask")
    IPV_4_NET_MASK("ipv4-net-mask"),
    @XmlEnumValue("ipv6-addr")
    IPV_6_ADDR("ipv6-addr"),
    @XmlEnumValue("ipv6-addr-hex")
    IPV_6_ADDR_HEX("ipv6-addr-hex"),
    @XmlEnumValue("ipv6-net")
    IPV_6_NET("ipv6-net"),
    @XmlEnumValue("ipv6-net-mask")
    IPV_6_NET_MASK("ipv6-net-mask");
    private final String value;

    AddressCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddressCategory fromValue(String v) {
        for (AddressCategory c: AddressCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
