//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Alert complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Alert">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Analyzer" type="{http://iana.org/idmef}Analyzer"/>
 *         &lt;element name="CreateTime" type="{http://iana.org/idmef}TimeWithNtpstamp"/>
 *         &lt;element name="DetectTime" type="{http://iana.org/idmef}TimeWithNtpstamp" minOccurs="0"/>
 *         &lt;element name="AnalyzerTime" type="{http://iana.org/idmef}TimeWithNtpstamp" minOccurs="0"/>
 *         &lt;element name="Source" type="{http://iana.org/idmef}Source" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Target" type="{http://iana.org/idmef}Target" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Classification" type="{http://iana.org/idmef}Classification"/>
 *         &lt;element name="Assessment" type="{http://iana.org/idmef}Assessment" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ToolAlert" type="{http://iana.org/idmef}ToolAlert"/>
 *           &lt;element name="OverflowAlert" type="{http://iana.org/idmef}OverflowAlert"/>
 *           &lt;element name="CorrelationAlert" type="{http://iana.org/idmef}CorrelationAlert"/>
 *         &lt;/choice>
 *         &lt;element name="AdditionalData" type="{http://iana.org/idmef}AdditionalData" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="messageid" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Alert", propOrder = {
    "analyzer",
    "createTime",
    "detectTime",
    "analyzerTime",
    "source",
    "target",
    "classification",
    "assessment",
    "toolAlert",
    "overflowAlert",
    "correlationAlert",
    "additionalData"
})
public class Alert {

    @XmlElement(name = "Analyzer", required = true)
    protected Analyzer analyzer;
    @XmlElement(name = "CreateTime", required = true)
    protected TimeWithNtpstamp createTime;
    @XmlElement(name = "DetectTime")
    protected TimeWithNtpstamp detectTime;
    @XmlElement(name = "AnalyzerTime")
    protected TimeWithNtpstamp analyzerTime;
    @XmlElement(name = "Source")
    protected List<Source> source;
    @XmlElement(name = "Target")
    protected List<Target> target;
    @XmlElement(name = "Classification", required = true)
    protected Classification classification;
    @XmlElement(name = "Assessment")
    protected Assessment assessment;
    @XmlElement(name = "ToolAlert")
    protected ToolAlert toolAlert;
    @XmlElement(name = "OverflowAlert")
    protected OverflowAlert overflowAlert;
    @XmlElement(name = "CorrelationAlert")
    protected CorrelationAlert correlationAlert;
    @XmlElement(name = "AdditionalData")
    protected List<AdditionalData> additionalData;
    @XmlAttribute(name = "messageid")
    protected String messageid;

    /**
     * Gets the value of the analyzer property.
     * 
     * @return
     *     possible object is
     *     {@link Analyzer }
     *     
     */
    public Analyzer getAnalyzer() {
        return analyzer;
    }

    /**
     * Sets the value of the analyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Analyzer }
     *     
     */
    public void setAnalyzer(Analyzer value) {
        this.analyzer = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeWithNtpstamp }
     *     
     */
    public TimeWithNtpstamp getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeWithNtpstamp }
     *     
     */
    public void setCreateTime(TimeWithNtpstamp value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the detectTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeWithNtpstamp }
     *     
     */
    public TimeWithNtpstamp getDetectTime() {
        return detectTime;
    }

    /**
     * Sets the value of the detectTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeWithNtpstamp }
     *     
     */
    public void setDetectTime(TimeWithNtpstamp value) {
        this.detectTime = value;
    }

    /**
     * Gets the value of the analyzerTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeWithNtpstamp }
     *     
     */
    public TimeWithNtpstamp getAnalyzerTime() {
        return analyzerTime;
    }

    /**
     * Sets the value of the analyzerTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeWithNtpstamp }
     *     
     */
    public void setAnalyzerTime(TimeWithNtpstamp value) {
        this.analyzerTime = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the source property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Source }
     * 
     * 
     */
    public List<Source> getSource() {
        if (source == null) {
            source = new ArrayList<Source>();
        }
        return this.source;
    }

    /**
     * Gets the value of the target property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the target property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Target }
     * 
     * 
     */
    public List<Target> getTarget() {
        if (target == null) {
            target = new ArrayList<Target>();
        }
        return this.target;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link Classification }
     *     
     */
    public Classification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classification }
     *     
     */
    public void setClassification(Classification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the assessment property.
     * 
     * @return
     *     possible object is
     *     {@link Assessment }
     *     
     */
    public Assessment getAssessment() {
        return assessment;
    }

    /**
     * Sets the value of the assessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assessment }
     *     
     */
    public void setAssessment(Assessment value) {
        this.assessment = value;
    }

    /**
     * Gets the value of the toolAlert property.
     * 
     * @return
     *     possible object is
     *     {@link ToolAlert }
     *     
     */
    public ToolAlert getToolAlert() {
        return toolAlert;
    }

    /**
     * Sets the value of the toolAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolAlert }
     *     
     */
    public void setToolAlert(ToolAlert value) {
        this.toolAlert = value;
    }

    /**
     * Gets the value of the overflowAlert property.
     * 
     * @return
     *     possible object is
     *     {@link OverflowAlert }
     *     
     */
    public OverflowAlert getOverflowAlert() {
        return overflowAlert;
    }

    /**
     * Sets the value of the overflowAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverflowAlert }
     *     
     */
    public void setOverflowAlert(OverflowAlert value) {
        this.overflowAlert = value;
    }

    /**
     * Gets the value of the correlationAlert property.
     * 
     * @return
     *     possible object is
     *     {@link CorrelationAlert }
     *     
     */
    public CorrelationAlert getCorrelationAlert() {
        return correlationAlert;
    }

    /**
     * Sets the value of the correlationAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrelationAlert }
     *     
     */
    public void setCorrelationAlert(CorrelationAlert value) {
        this.correlationAlert = value;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalData }
     * 
     * 
     */
    public List<AdditionalData> getAdditionalData() {
        if (additionalData == null) {
            additionalData = new ArrayList<AdditionalData>();
        }
        return this.additionalData;
    }

    /**
     * Gets the value of the messageid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageid() {
        if (messageid == null) {
            return "0";
        } else {
            return messageid;
        }
    }

    /**
     * Sets the value of the messageid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageid(String value) {
        this.messageid = value;
    }

}
