/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Assessment complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Assessment"&gt;
 *
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *
 *       &lt;sequence&gt;
 *         &lt;element name="Impact" type="{http://iana.org/idmef}Impact" minOccurs="0"/&gt;
 *         &lt;element name="Action" type="{http://iana.org/idmef}Action" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Confidence" type="{http://iana.org/idmef}Confidence" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Assessment", propOrder = { "impact", "action", "confidence" })
public class Assessment implements Serializable {
    
    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = 4535824634479299259L;
    @XmlElement(name = "Impact")
    protected Impact impact;
    @XmlElement(name = "Action")
    protected List<Action> action;
    @XmlElement(name = "Confidence")
    protected Confidence confidence;
    
    /**
     * Gets the value of the impact property.
     * 
     * @return
     *         possible object is
     *         {@link Impact }
     * 
     */
    public Impact getImpact() {
        return impact;
    }
    
    /**
     * Sets the value of the impact property.
     * 
     * @param value
     *            allowed object is
     *            {@link Impact }
     * 
     */
    public void setImpact(Impact value) {
        this.impact = value;
    }
    
    /**
     * Gets the value of the action property.
     * 
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the action
     * property.
     * 
     * 
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAction().add(newItem);
     * </pre>
     * 
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link Action }
     * 
     * @return the value of the action property.
     */
    public List<Action> getAction() {
        if (action == null) {
            action = new ArrayList<Action>();
        }
        return this.action;
    }
    
    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *         possible object is
     *         {@link Confidence }
     * 
     */
    public Confidence getConfidence() {
        return confidence;
    }
    
    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *            allowed object is
     *            {@link Confidence }
     * 
     */
    public void setConfidence(Confidence value) {
        this.confidence = value;
    }
    
}
