/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Checksum complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Checksum"&gt;
 *
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *
 *       &lt;sequence&gt;
 *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="algorithm" use="required" type="{http://iana.org/idmef}checksum-algorithm" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Checksum", propOrder = { "value", "key" })
public class Checksum implements Serializable {
    
    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = -8937745856381866586L;
    @XmlElement(required = true)
    protected String value;
    protected String key;
    @XmlAttribute(name = "algorithm", required = true)
    protected ChecksumAlgorithm algorithm;
    
    /**
     * Gets the value of the value property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getValue() {
        return value;
    }
    
    /**
     * Sets the value of the value property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setValue(String value) {
        this.value = value;
    }
    
    /**
     * Gets the value of the key property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getKey() {
        return key;
    }
    
    /**
     * Sets the value of the key property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setKey(String value) {
        this.key = value;
    }
    
    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *         possible object is
     *         {@link ChecksumAlgorithm }
     * 
     */
    public ChecksumAlgorithm getAlgorithm() {
        return algorithm;
    }
    
    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *            allowed object is
     *            {@link ChecksumAlgorithm }
     * 
     */
    public void setAlgorithm(ChecksumAlgorithm value) {
        this.algorithm = value;
    }
    
}
