/**
 * IDMEF Package for JAVA
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 * 
 * License Notice
 * 
 *   This file is subject to the terms and conditions defined in
 *   file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 *   Edits and bug-fixes:
 *     Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 *   Auto-generated files:
 *     This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 *     Reference Implementation, v2.2.8-b130911.1802 
 *     See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 *
 *   IDMEF Schema:
 *     Copyright (c) 2008 IETF Trust and the persons identified as the
 *     IDMEF document authors.  All rights reserved.
 *     See https://tools.ietf.org/html/bcp78 for the complete license 
 *     document.
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for checksum-algorithm.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="checksum-algorithm">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="MD4"/>
 *     &lt;enumeration value="MD5"/>
 *     &lt;enumeration value="SHA1"/>
 *     &lt;enumeration value="SHA2-256"/>
 *     &lt;enumeration value="SHA2-384"/>
 *     &lt;enumeration value="SHA2-512"/>
 *     &lt;enumeration value="CRC-32"/>
 *     &lt;enumeration value="Haval"/>
 *     &lt;enumeration value="Tiger"/>
 *     &lt;enumeration value="Gost"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "checksum-algorithm")
@XmlEnum
public enum ChecksumAlgorithm implements Serializable {

    @XmlEnumValue("MD4")
    MD_4("MD4"),
    @XmlEnumValue("MD5")
    MD_5("MD5"),
    @XmlEnumValue("SHA1")
    SHA_1("SHA1"),
    @XmlEnumValue("SHA2-256")
    SHA_2_256("SHA2-256"),
    @XmlEnumValue("SHA2-384")
    SHA_2_384("SHA2-384"),
    @XmlEnumValue("SHA2-512")
    SHA_2_512("SHA2-512"),
    @XmlEnumValue("CRC-32")
    CRC_32("CRC-32"),
    @XmlEnumValue("Haval")
    HAVAL("Haval"),
    @XmlEnumValue("Tiger")
    TIGER("Tiger"),
    @XmlEnumValue("Gost")
    GOST("Gost");
    private final String value;

    ChecksumAlgorithm(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChecksumAlgorithm fromValue(String v) {
        for (ChecksumAlgorithm c: ChecksumAlgorithm.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
