/**
 * IDMEF Package for JAVA
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 * 
 * License Notice
 * 
 *   This file is subject to the terms and conditions defined in
 *   file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 *   Edits and bug-fixes:
 *     Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 *   Auto-generated files:
 *     This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 *     Reference Implementation, v2.2.8-b130911.1802 
 *     See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 *
 *   IDMEF Schema:
 *     Copyright (c) 2008 IETF Trust and the persons identified as the
 *     IDMEF document authors.  All rights reserved.
 *     See https://tools.ietf.org/html/bcp78 for the complete license 
 *     document.
 */

package org.iana.idmef;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for File complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="File">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="create-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="modify-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="access-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="data-size" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="disk-size" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="FileAccess" type="{http://iana.org/idmef}FileAccess" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Linkage" type="{http://iana.org/idmef}Linkage" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Inode" type="{http://iana.org/idmef}Inode" minOccurs="0"/>
 *         &lt;element name="Checksum" type="{http://iana.org/idmef}Checksum" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ident" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="category" use="required" type="{http://iana.org/idmef}file-category" />
 *       &lt;attribute name="fstype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="file-type" type="{http://iana.org/idmef}mime-type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "File", propOrder = {
    "name",
    "path",
    "createTime",
    "modifyTime",
    "accessTime",
    "dataSize",
    "diskSize",
    "fileAccess",
    "linkage",
    "inode",
    "checksum"
})
public class File implements Serializable {

    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = 4775234627874714786L;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(name = "create-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createTime;
    @XmlElement(name = "modify-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modifyTime;
    @XmlElement(name = "access-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar accessTime;
    @XmlElement(name = "data-size")
    protected BigInteger dataSize;
    @XmlElement(name = "disk-size")
    protected BigInteger diskSize;
    @XmlElement(name = "FileAccess")
    protected List<FileAccess> fileAccess;
    @XmlElement(name = "Linkage")
    protected List<Linkage> linkage;
    @XmlElement(name = "Inode")
    protected Inode inode;
    @XmlElement(name = "Checksum")
    protected List<Checksum> checksum;
    @XmlAttribute(name = "ident")
    protected String ident;
    @XmlAttribute(name = "category", required = true)
    protected FileCategory category;
    @XmlAttribute(name = "fstype", required = true)
    protected String fstype;
    @XmlAttribute(name = "file-type")
    protected String fileType;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateTime(XMLGregorianCalendar value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the modifyTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModifyTime() {
        return modifyTime;
    }

    /**
     * Sets the value of the modifyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModifyTime(XMLGregorianCalendar value) {
        this.modifyTime = value;
    }

    /**
     * Gets the value of the accessTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccessTime() {
        return accessTime;
    }

    /**
     * Sets the value of the accessTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccessTime(XMLGregorianCalendar value) {
        this.accessTime = value;
    }

    /**
     * Gets the value of the dataSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDataSize() {
        return dataSize;
    }

    /**
     * Sets the value of the dataSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDataSize(BigInteger value) {
        this.dataSize = value;
    }

    /**
     * Gets the value of the diskSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiskSize() {
        return diskSize;
    }

    /**
     * Sets the value of the diskSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiskSize(BigInteger value) {
        this.diskSize = value;
    }

    /**
     * Gets the value of the fileAccess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileAccess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileAccess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileAccess }
     * 
     * 
     */
    public List<FileAccess> getFileAccess() {
        if (fileAccess == null) {
            fileAccess = new ArrayList<FileAccess>();
        }
        return this.fileAccess;
    }

    /**
     * Gets the value of the linkage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Linkage }
     * 
     * 
     */
    public List<Linkage> getLinkage() {
        if (linkage == null) {
            linkage = new ArrayList<Linkage>();
        }
        return this.linkage;
    }

    /**
     * Gets the value of the inode property.
     * 
     * @return
     *     possible object is
     *     {@link Inode }
     *     
     */
    public Inode getInode() {
        return inode;
    }

    /**
     * Sets the value of the inode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inode }
     *     
     */
    public void setInode(Inode value) {
        this.inode = value;
    }

    /**
     * Gets the value of the checksum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the checksum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChecksum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Checksum }
     * 
     * 
     */
    public List<Checksum> getChecksum() {
        if (checksum == null) {
            checksum = new ArrayList<Checksum>();
        }
        return this.checksum;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdent() {
        if (ident == null) {
            return "0";
        } else {
            return ident;
        }
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdent(String value) {
        this.ident = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link FileCategory }
     *     
     */
    public FileCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileCategory }
     *     
     */
    public void setCategory(FileCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the fstype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFstype() {
        return fstype;
    }

    /**
     * Sets the value of the fstype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFstype(String value) {
        this.fstype = value;
    }

    /**
     * Gets the value of the fileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * Sets the value of the fileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileType(String value) {
        this.fileType = value;
    }

}
