/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for id-type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;simpleType name="id-type"&gt;
 *
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *
 *     &lt;enumeration value="current-user"/&gt;
 *     &lt;enumeration value="original-user"/&gt;
 *     &lt;enumeration value="target-user"/&gt;
 *     &lt;enumeration value="user-privs"/&gt;
 *     &lt;enumeration value="current-group"/&gt;
 *     &lt;enumeration value="group-privs"/&gt;
 *     &lt;enumeration value="other-privs"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "id-type")
@XmlEnum
public enum IdType implements Serializable {
    
    @XmlEnumValue("current-user")
    CURRENT_USER("current-user"), @XmlEnumValue("original-user")
    ORIGINAL_USER("original-user"), @XmlEnumValue("target-user")
    TARGET_USER("target-user"), @XmlEnumValue("user-privs")
    USER_PRIVS("user-privs"), @XmlEnumValue("current-group")
    CURRENT_GROUP("current-group"), @XmlEnumValue("group-privs")
    GROUP_PRIVS("group-privs"), @XmlEnumValue("other-privs")
    OTHER_PRIVS("other-privs");
    private final String value;
    
    IdType(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static IdType fromValue(String v) {
        for (IdType c : IdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    
}
