//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for id-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="id-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="current-user"/>
 *     &lt;enumeration value="original-user"/>
 *     &lt;enumeration value="target-user"/>
 *     &lt;enumeration value="user-privs"/>
 *     &lt;enumeration value="current-group"/>
 *     &lt;enumeration value="group-privs"/>
 *     &lt;enumeration value="other-privs"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "id-type")
@XmlEnum
public enum IdType {

    @XmlEnumValue("current-user")
    CURRENT_USER("current-user"),
    @XmlEnumValue("original-user")
    ORIGINAL_USER("original-user"),
    @XmlEnumValue("target-user")
    TARGET_USER("target-user"),
    @XmlEnumValue("user-privs")
    USER_PRIVS("user-privs"),
    @XmlEnumValue("current-group")
    CURRENT_GROUP("current-group"),
    @XmlEnumValue("group-privs")
    GROUP_PRIVS("group-privs"),
    @XmlEnumValue("other-privs")
    OTHER_PRIVS("other-privs");
    private final String value;

    IdType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdType fromValue(String v) {
        for (IdType c: IdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
