//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for impact-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="impact-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="admin"/>
 *     &lt;enumeration value="dos"/>
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="recon"/>
 *     &lt;enumeration value="user"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "impact-type")
@XmlEnum
public enum ImpactType {

    @XmlEnumValue("admin")
    ADMIN("admin"),
    @XmlEnumValue("dos")
    DOS("dos"),
    @XmlEnumValue("file")
    FILE("file"),
    @XmlEnumValue("recon")
    RECON("recon"),
    @XmlEnumValue("user")
    USER("user"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ImpactType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ImpactType fromValue(String v) {
        for (ImpactType c: ImpactType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
