//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Impact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Impact">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="severity" type="{http://iana.org/idmef}impact-severity" />
 *       &lt;attribute name="completion" type="{http://iana.org/idmef}impact-completion" />
 *       &lt;attribute name="type" type="{http://iana.org/idmef}impact-type" default="other" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Impact", propOrder = {
    "value"
})
public class Impact {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "severity")
    protected ImpactSeverity severity;
    @XmlAttribute(name = "completion")
    protected ImpactCompletion completion;
    @XmlAttribute(name = "type")
    protected ImpactType type;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link ImpactSeverity }
     *     
     */
    public ImpactSeverity getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpactSeverity }
     *     
     */
    public void setSeverity(ImpactSeverity value) {
        this.severity = value;
    }

    /**
     * Gets the value of the completion property.
     * 
     * @return
     *     possible object is
     *     {@link ImpactCompletion }
     *     
     */
    public ImpactCompletion getCompletion() {
        return completion;
    }

    /**
     * Sets the value of the completion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpactCompletion }
     *     
     */
    public void setCompletion(ImpactCompletion value) {
        this.completion = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ImpactType }
     *     
     */
    public ImpactType getType() {
        if (type == null) {
            return ImpactType.OTHER;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpactType }
     *     
     */
    public void setType(ImpactType value) {
        this.type = value;
    }

}
