/**
 * IDMEF Package for JAVA
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 * 
 * License Notice
 * 
 *   This file is subject to the terms and conditions defined in
 *   file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 *   Edits and bug-fixes:
 *     Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 *   Auto-generated files:
 *     This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 *     Reference Implementation, v2.2.8-b130911.1802 
 *     See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 *
 *   IDMEF Schema:
 *     Copyright (c) 2008 IETF Trust and the persons identified as the
 *     IDMEF document authors.  All rights reserved.
 *     See https://tools.ietf.org/html/bcp78 for the complete license 
 *     document.
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Inode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Inode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="change-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="major-device" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="minor-device" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="c-major-device" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="c-minor-device" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Inode", propOrder = {
    "changeTime",
    "number",
    "majorDevice",
    "minorDevice",
    "cMajorDevice",
    "cMinorDevice"
})
public class Inode implements Serializable {

    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = -8831252480429741209L;
    @XmlElement(name = "change-time")
    protected String changeTime;
    protected String number;
    @XmlElement(name = "major-device")
    protected String majorDevice;
    @XmlElement(name = "minor-device")
    protected String minorDevice;
    @XmlElement(name = "c-major-device")
    protected String cMajorDevice;
    @XmlElement(name = "c-minor-device")
    protected String cMinorDevice;

    /**
     * Gets the value of the changeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeTime() {
        return changeTime;
    }

    /**
     * Sets the value of the changeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeTime(String value) {
        this.changeTime = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the majorDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorDevice() {
        return majorDevice;
    }

    /**
     * Sets the value of the majorDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorDevice(String value) {
        this.majorDevice = value;
    }

    /**
     * Gets the value of the minorDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorDevice() {
        return minorDevice;
    }

    /**
     * Sets the value of the minorDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorDevice(String value) {
        this.minorDevice = value;
    }

    /**
     * Gets the value of the cMajorDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMajorDevice() {
        return cMajorDevice;
    }

    /**
     * Sets the value of the cMajorDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMajorDevice(String value) {
        this.cMajorDevice = value;
    }

    /**
     * Gets the value of the cMinorDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMinorDevice() {
        return cMinorDevice;
    }

    /**
     * Sets the value of the cMinorDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMinorDevice(String value) {
        this.cMinorDevice = value;
    }

}
