/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Linkage complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Linkage"&gt;
 *
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="File" type="{http://iana.org/idmef}File"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="category" use="required" type="{http://iana.org/idmef}linkage-category" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Linkage", propOrder = { "name", "path", "file" })
public class Linkage implements Serializable {
    
    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = 3843811910801347448L;
    protected String name;
    protected String path;
    @XmlElement(name = "File")
    protected File file;
    @XmlAttribute(name = "category", required = true)
    protected LinkageCategory category;
    
    /**
     * Gets the value of the name property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getName() {
        return name;
    }
    
    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }
    
    /**
     * Gets the value of the path property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getPath() {
        return path;
    }
    
    /**
     * Sets the value of the path property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setPath(String value) {
        this.path = value;
    }
    
    /**
     * Gets the value of the file property.
     * 
     * @return
     *         possible object is
     *         {@link File }
     * 
     */
    public File getFile() {
        return file;
    }
    
    /**
     * Sets the value of the file property.
     * 
     * @param value
     *            allowed object is
     *            {@link File }
     * 
     */
    public void setFile(File value) {
        this.file = value;
    }
    
    /**
     * Gets the value of the category property.
     * 
     * @return
     *         possible object is
     *         {@link LinkageCategory }
     * 
     */
    public LinkageCategory getCategory() {
        return category;
    }
    
    /**
     * Sets the value of the category property.
     * 
     * @param value
     *            allowed object is
     *            {@link LinkageCategory }
     * 
     */
    public void setCategory(LinkageCategory value) {
        this.category = value;
    }
    
}
