//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for linkage-category.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="linkage-category">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="hard-link"/>
 *     &lt;enumeration value="mount-point"/>
 *     &lt;enumeration value="reparse-point"/>
 *     &lt;enumeration value="shortcut"/>
 *     &lt;enumeration value="stream"/>
 *     &lt;enumeration value="symbolic-link"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "linkage-category")
@XmlEnum
public enum LinkageCategory {

    @XmlEnumValue("hard-link")
    HARD_LINK("hard-link"),
    @XmlEnumValue("mount-point")
    MOUNT_POINT("mount-point"),
    @XmlEnumValue("reparse-point")
    REPARSE_POINT("reparse-point"),
    @XmlEnumValue("shortcut")
    SHORTCUT("shortcut"),
    @XmlEnumValue("stream")
    STREAM("stream"),
    @XmlEnumValue("symbolic-link")
    SYMBOLIC_LINK("symbolic-link");
    private final String value;

    LinkageCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LinkageCategory fromValue(String v) {
        for (LinkageCategory c: LinkageCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
