/**
 * IDMEF Package for JAVA
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 * 
 * License Notice
 * 
 *   This file is subject to the terms and conditions defined in
 *   file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 *   Edits and bug-fixes:
 *     Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 *   Auto-generated files:
 *     This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 *     Reference Implementation, v2.2.8-b130911.1802 
 *     See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 *
 *   IDMEF Schema:
 *     Copyright (c) 2008 IETF Trust and the persons identified as the
 *     IDMEF document authors.  All rights reserved.
 *     See https://tools.ietf.org/html/bcp78 for the complete license 
 *     document.
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for linkage-category.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="linkage-category">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="hard-link"/>
 *     &lt;enumeration value="mount-point"/>
 *     &lt;enumeration value="reparse-point"/>
 *     &lt;enumeration value="shortcut"/>
 *     &lt;enumeration value="stream"/>
 *     &lt;enumeration value="symbolic-link"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "linkage-category")
@XmlEnum
public enum LinkageCategory implements Serializable {

    @XmlEnumValue("hard-link")
    HARD_LINK("hard-link"),
    @XmlEnumValue("mount-point")
    MOUNT_POINT("mount-point"),
    @XmlEnumValue("reparse-point")
    REPARSE_POINT("reparse-point"),
    @XmlEnumValue("shortcut")
    SHORTCUT("shortcut"),
    @XmlEnumValue("stream")
    STREAM("stream"),
    @XmlEnumValue("symbolic-link")
    SYMBOLIC_LINK("symbolic-link");
    private final String value;

    LinkageCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LinkageCategory fromValue(String v) {
        for (LinkageCategory c: LinkageCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
