//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import java.math.BigInteger;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iana.idmef package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Heartbeat_QNAME = new QName("http://iana.org/idmef", "Heartbeat");
    private final static QName _Alert_QNAME = new QName("http://iana.org/idmef", "Alert");
    private final static QName _IDMEFMessage_QNAME = new QName("http://iana.org/idmef", "IDMEF-Message");
    private final static QName _UserIdNumber_QNAME = new QName("http://iana.org/idmef", "number");
    private final static QName _UserIdName_QNAME = new QName("http://iana.org/idmef", "name");
    private final static QName _NodeAddress_QNAME = new QName("http://iana.org/idmef", "Address");
    private final static QName _NodeLocation_QNAME = new QName("http://iana.org/idmef", "location");
    private final static QName _ServiceSNMPService_QNAME = new QName("http://iana.org/idmef", "SNMPService");
    private final static QName _ServiceProtocol_QNAME = new QName("http://iana.org/idmef", "protocol");
    private final static QName _ServicePort_QNAME = new QName("http://iana.org/idmef", "port");
    private final static QName _ServiceWebService_QNAME = new QName("http://iana.org/idmef", "WebService");
    private final static QName _ServicePortlist_QNAME = new QName("http://iana.org/idmef", "portlist");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iana.idmef
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Heartbeat }
     * 
     */
    public Heartbeat createHeartbeat() {
        return new Heartbeat();
    }

    /**
     * Create an instance of {@link Alert }
     * 
     */
    public Alert createAlert() {
        return new Alert();
    }

    /**
     * Create an instance of {@link IDMEFMessage }
     * 
     */
    public IDMEFMessage createIDMEFMessage() {
        return new IDMEFMessage();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link Analyzer }
     * 
     */
    public Analyzer createAnalyzer() {
        return new Analyzer();
    }

    /**
     * Create an instance of {@link Confidence }
     * 
     */
    public Confidence createConfidence() {
        return new Confidence();
    }

    /**
     * Create an instance of {@link Checksum }
     * 
     */
    public Checksum createChecksum() {
        return new Checksum();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Permission }
     * 
     */
    public Permission createPermission() {
        return new Permission();
    }

    /**
     * Create an instance of {@link AdditionalData }
     * 
     */
    public AdditionalData createAdditionalData() {
        return new AdditionalData();
    }

    /**
     * Create an instance of {@link Impact }
     * 
     */
    public Impact createImpact() {
        return new Impact();
    }

    /**
     * Create an instance of {@link FileAccess }
     * 
     */
    public FileAccess createFileAccess() {
        return new FileAccess();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link WebService }
     * 
     */
    public WebService createWebService() {
        return new WebService();
    }

    /**
     * Create an instance of {@link Assessment }
     * 
     */
    public Assessment createAssessment() {
        return new Assessment();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Xmltext }
     * 
     */
    public Xmltext createXmltext() {
        return new Xmltext();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link TimeWithNtpstamp }
     * 
     */
    public TimeWithNtpstamp createTimeWithNtpstamp() {
        return new TimeWithNtpstamp();
    }

    /**
     * Create an instance of {@link SNMPService }
     * 
     */
    public SNMPService createSNMPService() {
        return new SNMPService();
    }

    /**
     * Create an instance of {@link Linkage }
     * 
     */
    public Linkage createLinkage() {
        return new Linkage();
    }

    /**
     * Create an instance of {@link CorrelationAlert }
     * 
     */
    public CorrelationAlert createCorrelationAlert() {
        return new CorrelationAlert();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Inode }
     * 
     */
    public Inode createInode() {
        return new Inode();
    }

    /**
     * Create an instance of {@link OverflowAlert }
     * 
     */
    public OverflowAlert createOverflowAlert() {
        return new OverflowAlert();
    }

    /**
     * Create an instance of {@link UserId }
     * 
     */
    public UserId createUserId() {
        return new UserId();
    }

    /**
     * Create an instance of {@link ToolAlert }
     * 
     */
    public ToolAlert createToolAlert() {
        return new ToolAlert();
    }

    /**
     * Create an instance of {@link Alertident }
     * 
     */
    public Alertident createAlertident() {
        return new Alertident();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Heartbeat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "Heartbeat")
    public JAXBElement<Heartbeat> createHeartbeat(Heartbeat value) {
        return new JAXBElement<Heartbeat>(_Heartbeat_QNAME, Heartbeat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Alert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "Alert")
    public JAXBElement<Alert> createAlert(Alert value) {
        return new JAXBElement<Alert>(_Alert_QNAME, Alert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IDMEFMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "IDMEF-Message")
    public JAXBElement<IDMEFMessage> createIDMEFMessage(IDMEFMessage value) {
        return new JAXBElement<IDMEFMessage>(_IDMEFMessage_QNAME, IDMEFMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "number", scope = UserId.class)
    public JAXBElement<BigInteger> createUserIdNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserIdNumber_QNAME, BigInteger.class, UserId.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "name", scope = UserId.class)
    public JAXBElement<String> createUserIdName(String value) {
        return new JAXBElement<String>(_UserIdName_QNAME, String.class, UserId.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "Address", scope = Node.class)
    public JAXBElement<Address> createNodeAddress(Address value) {
        return new JAXBElement<Address>(_NodeAddress_QNAME, Address.class, Node.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "name", scope = Node.class)
    public JAXBElement<String> createNodeName(String value) {
        return new JAXBElement<String>(_UserIdName_QNAME, String.class, Node.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "location", scope = Node.class)
    public JAXBElement<String> createNodeLocation(String value) {
        return new JAXBElement<String>(_NodeLocation_QNAME, String.class, Node.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SNMPService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "SNMPService", scope = Service.class)
    public JAXBElement<SNMPService> createServiceSNMPService(SNMPService value) {
        return new JAXBElement<SNMPService>(_ServiceSNMPService_QNAME, SNMPService.class, Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "protocol", scope = Service.class)
    public JAXBElement<String> createServiceProtocol(String value) {
        return new JAXBElement<String>(_ServiceProtocol_QNAME, String.class, Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "port", scope = Service.class)
    public JAXBElement<BigInteger> createServicePort(BigInteger value) {
        return new JAXBElement<BigInteger>(_ServicePort_QNAME, BigInteger.class, Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "WebService", scope = Service.class)
    public JAXBElement<WebService> createServiceWebService(WebService value) {
        return new JAXBElement<WebService>(_ServiceWebService_QNAME, WebService.class, Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "name", scope = Service.class)
    public JAXBElement<String> createServiceName(String value) {
        return new JAXBElement<String>(_UserIdName_QNAME, String.class, Service.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iana.org/idmef", name = "portlist", scope = Service.class)
    public JAXBElement<List<String>> createServicePortlist(List<String> value) {
        return new JAXBElement<List<String>>(_ServicePortlist_QNAME, ((Class) List.class), Service.class, ((List<String> ) value));
    }

}
