/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for OverflowAlert complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OverflowAlert"&gt;
 *
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *
 *       &lt;sequence&gt;
 *         &lt;element name="program" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="buffer" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OverflowAlert", propOrder = { "program", "size", "buffer" })
public class OverflowAlert implements Serializable {
    
    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = 3435282388721575196L;
    @XmlElement(required = true)
    protected String program;
    @XmlElement(required = true)
    protected String size;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] buffer;
    
    /**
     * Gets the value of the program property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getProgram() {
        return program;
    }
    
    /**
     * Sets the value of the program property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setProgram(String value) {
        this.program = value;
    }
    
    /**
     * Gets the value of the size property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getSize() {
        return size;
    }
    
    /**
     * Sets the value of the size property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setSize(String value) {
        this.size = value;
    }
    
    /**
     * Gets the value of the buffer property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public byte[] getBuffer() {
        return buffer;
    }
    
    /**
     * Sets the value of the buffer property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setBuffer(byte[] value) {
        this.buffer = value;
    }
    
}
