/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for reference-origin.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;simpleType name="reference-origin"&gt;
 *
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="vendor-specific"/&gt;
 *     &lt;enumeration value="user-specific"/&gt;
 *     &lt;enumeration value="bugtraqid"/&gt;
 *     &lt;enumeration value="cve"/&gt;
 *     &lt;enumeration value="osvdb"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "reference-origin")
@XmlEnum
public enum ReferenceOrigin implements Serializable {
    
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"), @XmlEnumValue("vendor-specific")
    VENDOR_SPECIFIC("vendor-specific"), @XmlEnumValue("user-specific")
    USER_SPECIFIC("user-specific"), @XmlEnumValue("bugtraqid")
    BUGTRAQID("bugtraqid"), @XmlEnumValue("cve")
    CVE("cve"), @XmlEnumValue("osvdb")
    OSVDB("osvdb");
    private final String value;
    
    ReferenceOrigin(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static ReferenceOrigin fromValue(String v) {
        for (ReferenceOrigin c : ReferenceOrigin.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    
}
