/**
 * IDMEF Package for JAVA
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 * 
 */

package org.iana.idmef;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Reference complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Reference"&gt;
 *
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="origin" type="{http://iana.org/idmef}reference-origin" default="unknown" /&gt;
 *       &lt;attribute name="meaning" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reference", propOrder = { "name", "url" })
public class Reference implements Serializable {
    
    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = -2218308209843961809L;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String url;
    @XmlAttribute(name = "origin")
    protected ReferenceOrigin origin;
    @XmlAttribute(name = "meaning")
    protected String meaning;
    
    /**
     * Gets the value of the name property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getName() {
        return name;
    }
    
    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }
    
    /**
     * Gets the value of the url property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getUrl() {
        return url;
    }
    
    /**
     * Sets the value of the url property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setUrl(String value) {
        this.url = value;
    }
    
    /**
     * Gets the value of the origin property.
     * 
     * @return
     *         possible object is
     *         {@link ReferenceOrigin }
     * 
     */
    public ReferenceOrigin getOrigin() {
        if (origin == null) {
            return ReferenceOrigin.UNKNOWN;
        }
        else {
            return origin;
        }
    }
    
    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *            allowed object is
     *            {@link ReferenceOrigin }
     * 
     */
    public void setOrigin(ReferenceOrigin value) {
        this.origin = value;
    }
    
    /**
     * Gets the value of the meaning property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getMeaning() {
        return meaning;
    }
    
    /**
     * Sets the value of the meaning property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setMeaning(String value) {
        this.meaning = value;
    }
    
}
