//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.14 at 11:09:23 AM CEST 
//


package org.iana.idmef;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Service complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Service">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="portlist" type="{http://iana.org/idmef}port-list"/>
 *         &lt;/choice>
 *         &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SNMPService" type="{http://iana.org/idmef}SNMPService" minOccurs="0"/>
 *         &lt;element name="WebService" type="{http://iana.org/idmef}WebService" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ident" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="ip_version" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="iana_protocol_number" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="iana_protocol_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Service", propOrder = {
    "content"
})
public class Service {

    @XmlElementRefs({
        @XmlElementRef(name = "name", namespace = "http://iana.org/idmef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "port", namespace = "http://iana.org/idmef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WebService", namespace = "http://iana.org/idmef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "portlist", namespace = "http://iana.org/idmef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SNMPService", namespace = "http://iana.org/idmef", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "protocol", namespace = "http://iana.org/idmef", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> content;
    @XmlAttribute(name = "ident")
    protected String ident;
    @XmlAttribute(name = "ip_version")
    protected BigInteger ipVersion;
    @XmlAttribute(name = "iana_protocol_number")
    protected BigInteger ianaProtocolNumber;
    @XmlAttribute(name = "iana_protocol_name")
    protected String ianaProtocolName;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Port" is used by two different parts of a schema. See: 
     * line 450 of file:/C:/Users/matti/Desktop/x/IDMEF-Schema.xsd
     * line 447 of file:/C:/Users/matti/Desktop/x/IDMEF-Schema.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link SNMPService }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link WebService }{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<?>>();
        }
        return this.content;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdent() {
        if (ident == null) {
            return "0";
        } else {
            return ident;
        }
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdent(String value) {
        this.ident = value;
    }

    /**
     * Gets the value of the ipVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIpVersion() {
        return ipVersion;
    }

    /**
     * Sets the value of the ipVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIpVersion(BigInteger value) {
        this.ipVersion = value;
    }

    /**
     * Gets the value of the ianaProtocolNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIanaProtocolNumber() {
        return ianaProtocolNumber;
    }

    /**
     * Sets the value of the ianaProtocolNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIanaProtocolNumber(BigInteger value) {
        this.ianaProtocolNumber = value;
    }

    /**
     * Gets the value of the ianaProtocolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIanaProtocolName() {
        return ianaProtocolName;
    }

    /**
     * Sets the value of the ianaProtocolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIanaProtocolName(String value) {
        this.ianaProtocolName = value;
    }

}
