/**
 * IDMEF Package for JAVA
 * 
 * License Notice
 * 
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 * 
 * Copyright Notice
 *
 * Edits and bug-fixes:
 * Copyright (c) 2017 Mattia Zago. All rights reserved.
 *
 * Auto-generated files:
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB)
 * Reference Implementation, v2.2.8-b130911.1802
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
 *
 * IDMEF Schema:
 * Copyright (c) 2008 IETF Trust and the persons identified as the
 * IDMEF document authors. All rights reserved.
 * See https://tools.ietf.org/html/bcp78 for the complete license
 * document.
 *
 * @author Mattia Zago - dev [at] zagomattia [dot] it
 * @version 0.0.1
 * @since 14/09/2017
 */

package org.iana.idmef;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for User complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="User"&gt;
 *
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *
 *       &lt;sequence&gt;
 *         &lt;element name="UserId" type="{http://iana.org/idmef}UserId" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ident" type="{http://www.w3.org/2001/XMLSchema}string" default="0" /&gt;
 *       &lt;attribute name="category" type="{http://iana.org/idmef}user-category" default="unknown" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "User", propOrder = { "userId" })
public class User implements Serializable {
    
    /**
     * Generated Serial Version UID.
     */
    private static final long serialVersionUID = -3754559936600387214L;
    @XmlElement(name = "UserId", required = true)
    protected List<UserId> userId;
    @XmlAttribute(name = "ident")
    protected String ident;
    @XmlAttribute(name = "category")
    protected UserCategory category;
    
    /**
     * Gets the value of the userId property.
     * 
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userId
     * property.
     * 
     * 
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getUserId().add(newItem);
     * </pre>
     * 
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link UserId }
     * 
     * 
     */
    public List<UserId> getUserId() {
        if (userId == null) {
            userId = new ArrayList<UserId>();
        }
        return this.userId;
    }
    
    /**
     * Gets the value of the ident property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getIdent() {
        if (ident == null) {
            return "0";
        }
        else {
            return ident;
        }
    }
    
    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *            allowed object is
     *            {@link String }
     * 
     */
    public void setIdent(String value) {
        this.ident = value;
    }
    
    /**
     * Gets the value of the category property.
     * 
     * @return
     *         possible object is
     *         {@link UserCategory }
     * 
     */
    public UserCategory getCategory() {
        if (category == null) {
            return UserCategory.UNKNOWN;
        }
        else {
            return category;
        }
    }
    
    /**
     * Sets the value of the category property.
     * 
     * @param value
     *            allowed object is
     *            {@link UserCategory }
     * 
     */
    public void setCategory(UserCategory value) {
        this.category = value;
    }
    
}
